[package]
name = "tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "1_variables_mutability"
path = "src/1_variables_mutability.rs"

[[bin]]
name = "2_data_types"
path = "src/2_data_types.rs"
